### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by jaime-ez** [thefrontside/frontmacs#100]
Hi, I followed the instruction and get this error when launching emacs:

![image](https://user-images.githubusercontent.com/4974776/34562776-9ab3b1ec-f12e-11e7-95ac-71edb4b353e2.png)

I'm using ubuntu 16.04
Any help would be much appreciated, thanks

**Comment by cowboyd** [comment]
@jaime-ez A broken install is so frustrating, so thanks for reporting this!

 It looks like you're using Emacs 24, and I'm not sure if we support it. Can you clear out your `.emacs.d` and try with Emacs 25?

**Comment by jaime-ez** [comment]
yes, that was it, thanks!
