### ISSUE TITLE
Spacemacs layer or package

### ISSUE THREAD

**Issue by tsutsarin** [thefrontside/frontmacs#110]
How this repo is related with Spacemacs?
Can I use Frontmacs with Spacemacs?
For example, can I install Frontmacs as Spacemacs layer or package?

**Comment by rberger** [comment]
I was wondering the same thing. Its not clear if one should start with a clean .emacs.d or can drop this in any arbitrarily complex customized emacs environment.

**Comment by cowboyd** [comment]
In reality, I think you'll experience the most success witha clean `.emacs.d` as it will probably conflict with a lot of packages. I haven't actually tried to use this with spacemacs, but there is a lot of overlap in what it's trying to accomplish, so your mileage may vary.

**Comment by ghost** [comment]
So why not to build on top of Spacemacs?

**Comment by gburnett** [comment]
I think that is answered in the `README.md`

>We've been satisfied users of many a starter kit over the years, from the original Emacs Starter Kit, to Prelude and Spacemacs. Most starter kits you come across begin with a fork. You clone the repo, and then you're off to the races maintaining your own version. Any customizations you make are made to files under version control and so upgrading and keeping up with the community is a constant battle of merges, rebases, throw-aways and ultimately do overs. We know because we've been there.

>This is painful enough when you're maintaining your own fork, but every time we wanted to make a customization from which the entire team could benefit, it involved everybody doing the same merge, rebase, throw-away dance. But, it turns out that Emacs has a mechanism to distribute elisp code without having to use git. It's called ELPA and it's awesome. You can think of it like a Ruby gem or an NPM package, and this is what Frontmacs uses for deployment.

>We don't want to maintain code, we just want to enter a few keystrokes and download more awesome. And that's what we get by using elisp packages to install Frontmacs. Now, anytime we fix a bug or make an improvement, the entire team can benefit with a simple upgrade.

**Comment by Robdel12** [comment]
Yeah, I personally don't want to build on top of Spacemacs. Spacemacs is a great package in itself, but I don't have any interest in using it (I've attempted a couple times).

**Comment by cowboyd** [comment]
@Robdel12 can we Close this since it appears like we've come to a conclusion?
