### ISSUE TITLE
nlinum over linum

### ISSUE THREAD

**Issue by rhoit** [thefrontside/frontmacs#111]
**linum** is very slow and since it redraws in each key press, which gives terrible flickes.

but similar look can be achived using **nlinum**

![screenshot_2018-01-07_23-32-31](https://user-images.githubusercontent.com/1684754/34652188-12b1f3e4-f403-11e7-96ec-5f28a01c83f3.png)

```elisp
     (require 'nlinum)

     (setq nlinum-delay t) ;; for smooth scrolling
     (setq nlinum-highlight-current-line t)
     (setq nlinum-format " %3d ")
     (nlinum-current-line "#your-fav-color") ;; in screen shot its *inverse-video* 
```

only downside is you **hlinum** might not work with **nlinum**, I haven't checked.

**Comment by cowboyd** [comment]
It looks like we use both? https://github.com/thefrontside/frontmacs/blob/master/frontmacs-windowing.el#L1-L2

https://github.com/thefrontside/frontmacs/blob/master/frontmacs-windowing.el#L38-L41

Maybe we need to revisit this? @rhoit what is the exact configuration you would recommend and why?



<blockquote><img src="https://avatars3.githubusercontent.com/u/223096?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/thefrontside/frontmacs">thefrontside/frontmacs</a></strong></div><div>frontmacs - A package-based, web-centric, customizable, awesome-by-default, acceptance-tested Emacs distribution curated by your friends at Frontside.</div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/223096?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/thefrontside/frontmacs">thefrontside/frontmacs</a></strong></div><div>frontmacs - A package-based, web-centric, customizable, awesome-by-default, acceptance-tested Emacs distribution curated by your friends at Frontside.</div></blockquote>

**Comment by rhoit** [comment]
nlinum is depreciate now.
