### ISSUE TITLE
enchancement:  zoom in/out reset with mouse and keyboard

### ISSUE THREAD

**Issue by rhoit** [thefrontside/frontmacs#112]
rather than using **zoom-frm** which didn't even work in my config of frontmacs
we could have simply binded to **text-scale-increase** and **text-scale-decrease**

of course add the C-mouse scroll, was missing in frontmacs!

```elisp
(global-set-key [C-mouse-4] 'text-scale-increase)
(global-set-key [(control ?+)] 'text-scale-increase)
(global-set-key [C-mouse-5] 'text-scale-decrease)
(global-set-key [(control ?-)] 'text-scale-decrease)
(global-set-key (kbd "C-0") '(lambda () (interactive)
							   (text-scale-adjust
								(- text-scale-mode-amount))
							   (text-scale-mode -1)))
```

**Comment by cowboyd** [comment]
Hmm, maybe we can use this as a fallback? 

The problem with `text-scale-increase` is that it only works for the current buffer, whereas every other buffer remains unaffected.

What we're trying to emulate is the behavior on the native operating system, where you increase the font size for an entire application, which is usually what you want.

I'm wondering why it didn't work? Is there a way to have `text-scale-adjust` work for the entire app?

**Comment by rhoit** [comment]
hmm.. didn't knew **zoom-frm** zoom all the buffers, since it didn't work for me.

> I'm wondering why it didn't work? Is there a way to have text-scale-adjust work for the entire app?

no idea me happy with single buffer zoom.
