### ISSUE TITLE
Smart parens does not recognize regular JavaScript expression delimiter as a pair

### ISSUE THREAD

**Issue by SamKeathley** [thefrontside/frontmacs#113]
If I surround text and hit the `/` it replaces the entire text with the `/`, but it should surround the text with a regular expression delimiter.

![2018-01-08 15 06 06](https://user-images.githubusercontent.com/25858667/34692392-9bf51e42-f485-11e7-8865-9289c5585170.gif)

**Comment by cowboyd** [comment]
😄
