### ISSUE TITLE
Consider removing scrollbars

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/frontmacs#114]
They are most un-elite.

**Comment by Robdel12** [comment]
Isn't this an OS setting? I don't have scrollbars in my emacs

**Comment by cowboyd** [comment]
`M-x describe-function` `scroll-bar-mode`

**Comment by Robdel12** [comment]
Huh, TIRL (Today I re-learned). Apparently I disabled this in my config: https://github.com/Robdel12/.emacs.d/blob/7aabcc82527cc0093567b69db04970949dbbbc34/initializers/window.el#L2

**Comment by cowboyd** [comment]
This is done with #120
