### ISSUE TITLE
Package vkill-20091203.1022 is unavailable

### ISSUE THREAD

**Issue by craiglyons** [thefrontside/frontmacs#126]
On a fresh install, I'm seeing the error in the issue title. Results of `--debug-init` are below.

emacs version `25.3.1`, installed with brew & `--gnutls` flag, mac os `10.13.4`.
Packages prior to vkill seem to be working, as far as I can tell, which rules out a blanket network issue.
I forked, killed the package locally, and set the `FRONTMACS_ARCHIVE` env var to point to my fork, but it still tries to install vkill.  (Sidebar, curious what I missed to be able to do that in the future for PRs.)

Thanks for looking into it!

```
Debugger entered--Lisp error: (error "Package ‘vkill-20091203.1022’ is unavailable")
  signal(error ("Package ‘vkill-20091203.1022’ is unavailable"))
  error("Package `%s-%s' is unavailable" vkill "20091203.1022")
  package-compute-transaction(([cl-struct-package-desc frontmacs (0 2 20) "Frontside config package for emacs" ((f (0 19 0)) (magit (2 8 0)) (git-link (0 4 5)) (git-timem$
  package-compute-transaction(nil ((frontmacs)))
  package-install(frontmacs t)
  (if (package-installed-p (quote frontmacs)) nil (package-refresh-contents) (package-install (quote frontmacs) t))
  eval-buffer(#<buffer  *load*-491559> nil "/Users/craiglyons/.emacs.d/init-frontmacs.el" nil t)  ; Reading at buffer position 2527
  load-with-code-conversion("/Users/craiglyons/.emacs.d/init-frontmacs.el" "/Users/craiglyons/.emacs.d/init-frontmacs.el" nil nil)
  load("/Users/craiglyons/.emacs.d/init-frontmacs.el")
  eval-buffer(#<buffer  *load*> nil "/Users/craiglyons/.emacs.d/init.el" nil t)  ; Reading at buffer position 361
  load-with-code-conversion("/Users/craiglyons/.emacs.d/init.el" "/Users/craiglyons/.emacs.d/init.el" t t)
  load("/Users/craiglyons/.emacs.d/init" t t)...
```

**Comment by Robdel12** [comment]
Hey @craiglyons thanks for the issue! I did a little bit of digging around and couldn't find `vkill` on either melpa or gnu package archives. 

@cowboyd I wonder if this apart of the emacs wiki no longer distributing packages for security reasons. I couldn't find it on any wikis but I did find this: https://github.com/emacsattic/vkill/blob/master/vkill.el

Should we do the same thing you did here with zoom-frm? https://github.com/thefrontside/frontmacs/commit/742a8089a8880075d07c5e0c0b78bd98c412a8c5

**Comment by craiglyons** [comment]
@Robdel12 Is there a way to work around this in the meantime? I have a local fork of the repo, but setting the `FRONTMACS_ARCHIVE` env var doesn't do the trick.  I'm blocked from using my frontmacs configuration entirely at the moment.

**Comment by craiglyons** [comment]
^ Quick workaround is to replace the frontmacs package with a local fork using `package-install-file`.
`init-frontmacs.el`
```
;; if frontmacs is not installed yet, install it.
(unless (package-installed-p 'frontmacs)
  (package-refresh-contents)
  (package-install-file '/Users/craiglyons/projects/contrib/frontmacs))
```

If there's interest in supporting this as an environment variable, I'll PR it at some point.

cc @gburnett

**Comment by Robdel12** [comment]
Hey @craiglyons! I think we've decided we're going to remove the vkill package since it's no longer on melpa or elpa. This _should_ be done today :)

**Comment by craiglyons** [comment]
Thanks @Robdel12!
Here's a PR that simply removes it, you're welcome to merge/close/assume it.
https://github.com/thefrontside/frontmacs/pull/127
