### ISSUE TITLE
Undefined Counsel-projectile key bindings

### ISSUE THREAD

**Issue by flexyford** [thefrontside/frontmacs#132]
When booting frontmacs for the first time on Emacs 26.2, the `C-c p` bindings would show up as `undefined`, although `M-x <any-projectile-command>` worked just fine. 

When viewing `package-list-packages` the `counsel-projectile` version is at `counsel-projectile-20190325.856`. However, frontmacs has a dependency on  `counsel-projectile-20171227.1315`, so I'm not sure why the version bump occurred on my end. 

Took me a bit to track this down, but I needed to add this line to `frontmacs-projectile.el`: 
[enabling-counsel-projectile-mode-when-emacs-starts](https://github.com/ericdanan/counsel-projectile#enabling-counsel-projectile-mode-when-emacs-starts)

>Note that starting with projectile version `1.1`, the projectile (and counsel-projectile) key bindings are only available after you select a keymap prefix for them. For instance, to select <kbd>C-c p</kbd> as prefix (the default prior to version `1.1`), you need to execute the following form:
> ```emacs-lisp
> (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
> ```

Happy to open a PR if others have come across this problem

**Comment by cowboyd** [comment]
Seems super legit to me... Now that counsel and counsel projectile are stable, should we depend on the stable releases too?

> Happy to open a PR if others have come across this problem.

Yass plz!!

**Comment by flexyford** [comment]
> Now that counsel and counsel projectile are stable, should we depend on the stable releases too?

👍
