### ISSUE TITLE
New buffers always open in new window

### ISSUE THREAD

**Issue by jlagarespo** [thefrontside/frontmacs#142]
I've been using Frontmacs for a while now, and it's been great so far :)
However, there's been something that I'd like to change and I haven't found anywhere how: every time you open a new buffer (find-file, shell, etc.) it opens in a separate window. This is not necessarily bad at the start, but eventually you end up just making a mess and go `C-x 1` to start over. I'd really like there to be an option to switch this to default Emacs behavior (if there isn't one already).
Thanks in advance.

**Comment by jlagarespo** [comment]
Never mind, I ended up figuring it out, it was a problem on my side with Popwin. Closing the issue.

**Comment by cowboyd** [comment]
@jlagarespo I'm glad that it all got resolved!

Would love to have any suggestions/contributions you may think worthwhile.

**Comment by jlagarespo** [comment]
I'm glad you're glad it got resolved :)
I honestly don't know if I can say much more though, I was using Popwin to close asterisk buffers automatically, and then decided that I wouldn't use it anymore, essentially because I didn't want that behavior anymore (for other reasons). For some reason it seemed to fix it, and I have no idea why it did to be honest.
