### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by gburnett** [thefrontside/frontmacs#144]
A fresh install of frontmacs fails for me just now.

```
Warning (initialization): An error occurred while loading ‘/home/gburnett/.emacs.d/init.el’:

error: Package ‘f-0.19.0’ is unavailable
```

Does [this dependency](https://github.com/rejeep/f.el/releases/tag/v0.20.0) need upgraded?

**Comment by cowboyd** [comment]
Hi @gburnett! Thanks for taking the time to report this issue. What version of emacs are you using?

I have had problems in the past where the certificates expired on older versions of emacs and so it was not longer able to fetch packages from some sources. If memory serves it was the main https://elpa.gnu.org (but don't quote me on that).


<blockquote><img src="favicon.png" width="48" align="right"><div><strong><a href="https://elpa.gnu.org/">GNU Emacs Lisp Package Archive</a></strong></div></blockquote>

**Comment by gburnett** [comment]
@cowboyd Ah, yes, it's an old one (26.1).  I'll try again with an up to date version.

**Comment by cowboyd** [comment]
Let me know how it works with 27.1

**Comment by gburnett** [comment]
Closing this issue now as installation works fine on 27.1
