### ISSUE TITLE
Directory navigation similar to IDO

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/frontmacs#36]

**Comment by wwilsman** [comment]
Swiper includes a library called [counsel](https://github.com/abo-abo/swiper/blob/master/counsel.el) that enables Ivy for find-file and several other functions. The hard part is getting used to RET on a directory opening dired instead of navigating into that directory.

**Comment by Robdel12** [comment]
> The hard part is getting used to RET on a directory opening dired instead of navigating into that directory.

That's exactly what we want to do. We want to navigate into that dir & not open dired

**Comment by cowboyd** [comment]
Have a look here:

http://oremacs.com/swiper/#minibuffer-key-bindings

Looks like `C-j` actually does already what we want, the question is, do we re-map, or just go with the flow?

**Comment by wwilsman** [comment]
Ah, I see now. `C-j` isn't too difficult to get used to, especially since I'm usually already holding `C` to navigate matches with `C-p` and `C-n`

**Comment by cowboyd** [comment]
And check it, there's a keychord! `TAB TAB` is bound to the same function. This library is well thought out.

**Comment by wwilsman** [comment]
That's what I've been using initially. I still catch myself hitting `RET` pretty frequently though.

**Comment by Robdel12** [comment]
I think the thing to come out of this is README docs. I think `TAB TAB` is actually pretty good and I'm already used to it.

**Comment by wwilsman** [comment]
This is fixed by 7b7d64a9b94263ba99c57c6b7bb2a39be360f7b2
