### ISSUE TITLE
Projectile Project list is not loaded the first time you try to switch projects.

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/frontmacs#58]
It looks like the project list is not getting populated on Emacs initialization. Instead, the first time you do project operations, it works.

I've found a workaround of running `projectile-cleanup-known-projects` which populates them.

![2017-04-17 08 50 12](https://cloud.githubusercontent.com/assets/4205/25090786/f504bd6a-234a-11e7-999d-f87bc8a183ac.gif)

**Comment by Robdel12** [comment]
Hmm, yeah I've been running into this too.

**Comment by cowboyd** [comment]
My guess is that _something_ is not getting initialized properly with projectile.
